import Head from "next/head";
import styles from "@/styles/Home.module.css";
import type { GoogleSheetResponse } from "@/types/google";
import { DateTime } from "luxon";
import { ResponsiveTimeRange } from "@nivo/calendar";

export default function Home({
  names,
  checkins,
  days,
}: {
  names: string[];
  checkins: boolean[][];
  days: string[];
}) {
  const calendarData = checkins.reduce((data, checkins, i) => {
    return [
      ...data,
      {
        day: days[i],
        value: checkins.filter((x) => x).length,
      },
    ];
  }, [] as { day: string; value: number }[]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.calendar}>
          <ResponsiveTimeRange
            data={calendarData}
            from={days[0]}
            to={days[days.length - 1]}
            emptyColor="#eeeeee"
            colors={["#61cdbb", "#97e3d5", "#e8c1a0", "#f47560"]}
            margin={{ top: 40, right: 40, bottom: 40, left: 40 }}
            dayBorderWidth={2}
            dayBorderColor="#ffffff"
          />
        </div>
      </main>
    </>
  );
}

const id = "1k-tnKWWB3q6XCF2ofav-yT_CGprIFMBTf9OPhvR8hlM";
async function getSheetData<T>(
  start: string,
  end: string,
  dimension: "COLUMNS" | "ROWS"
): Promise<GoogleSheetResponse<T>> {
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${id}/values/Sheet1!${start}:${end}?majorDimension=${dimension}&key=${process.env.GOOGLE_API_KEY}`;
  return fetch(url).then((res) => res.json());
}

export async function getServerSideProps() {
  const firstDay = DateTime.local(2022, 11, 28);
  const now = DateTime.now();
  const length = Math.ceil(now.diff(firstDay, "days").days);
  console.log(length);
  const days = new Array(length)
    .fill(undefined)
    .map((_, i) => firstDay.plus({ days: i }).toFormat("yyyy-MM-dd"));
  const [namesData, checkinData] = await Promise.all([
    getSheetData<string>("B5", "B15", "COLUMNS"),
    getSheetData<"TRUE" | "FALSE">("C5", "DX15", "COLUMNS"),
  ]);
  const checkins = checkinData?.values?.map((day) =>
    day.map((checkin) => checkin === "TRUE")
  );
  return {
    props: {
      names: namesData?.values?.[0],
      checkins: checkins.slice(0, length),
      days,
    },
  };
}
